version: "3.9"  # optional since v1.27.0
services:
    traefik:
        image: "traefik:v2.4"
        container_name: "traefik"
        command:
        #- "--log.level=DEBUG"
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
        - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
        #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
        - "--certificatesresolvers.myresolver.acme.email=plelldavid@gmail.com"
        - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
        ports:
        - "80:80"
        - "443:443"
        - "8080:8080"
        volumes:
        - "./letsencrypt:/letsencrypt"
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
    # whoami:
    #     image: "traefik/whoami"
    #     container_name: "simple-service"
    #     labels:
    #     - "traefik.enable=true"
    #     - "traefik.http.routers.whoami.rule=Host(`api.jamwallet.app`)"
    #     - "traefik.http.routers.whoami.entrypoints=websecure"
    #     - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    divvy-go:
        build: . #build with dockerfile
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`143.198.69.122`)"
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.tls.certresolver=myresolver"
        # ports:
        # - "443:443"