version: "3.3"  # optional since v1.27.0
services:
    traefik:
        image: traefik:2.1
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./traefik:/etc/traefik
            - /var/run/docker.sock:/var/run/docker.sock:ro
    divvy-go:
        image: "divvy-go:latest"
        # container_name: "divvy"
        # build: . #build with dockerfile
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.divvy-go.rule=Host(`api.jamwallet.app`)'
            - 'traefik.http.routers.divvy-go.tls=true'
            - 'traefik.http.routers.divvy-go.tls.certresolver=lets-encrypt'